### ISSUE TITLE
Potential bad build

### ISSUE THREAD

**Issue by avdata99** [ckan/ckan-solr#12]
for image `ckan/ckan-solr:2.10-solr9`

Github action gives an error:

<pre>
ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.11. Supported versions are [2.8, 2.9, 2.10]
</pre>

This worked until yesterday

**Comment by duttonw** [comment]
https://hub.docker.com/r/ckan/ckan-solr/tags
@amercader  you seem to have accidentally pushed 2.11 schema for 2.9 ~ master.


@avdata99  workaround for 2.9 is to use ckan-solr tag: "2.9-solr8" https://github.com/ckan/ckanext-validation/commit/c3b975d74fe52ef3a4dc8c5187c845f0a660df8b#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R34

for 2.10, you can try tag: [2.10-solr8](https://hub.docker.com/layers/ckan/ckan-solr/2.10-solr8/images/sha256-1d6eb186003c2bb3bfeaa20c2494a6ff5ade34b757627071fe70de167cc4bbc0?context=explore)

**Comment by amercader** [comment]
Sorry, will fix asap and put some extra checks in place

**Comment by amercader** [comment]
All images have the relevant schema version for the CKAN version they are targeting. I added another extra check to test this in #14

**Comment by avdata99** [comment]
Thanks @amercader. I didn't manage to find the error
