### ISSUE TITLE
Solr schema not altered to match CKAN version on latest CICD pipeline

### ISSUE THREAD

**Issue by duttonw** [ckan/ckan-solr#13]
Hi @amercader ,

I love what you are doing with this, sadly there is some hiccups which is now breaking anyone using the latests tags. We need to ensure 'tests' pass before pushing up to not have this occur in the future :).

## Workaround 

For those who are affected till its correct.

Update to use the solr8 images as they are not changed since Jul 5, 2023  
CKAN 2.10:  [2.10-solr8](https://hub.docker.com/layers/ckan/ckan-solr/2.10-solr8/images/sha256-1d6eb186003c2bb3bfeaa20c2494a6ff5ade34b757627071fe70de167cc4bbc0?context=explore)
CKAN 2.9:  [2.9-solr8](https://hub.docker.com/layers/ckan/ckan-solr/2.9-solr8/images/sha256-1d6eb186003c2bb3bfeaa20c2494a6ff5ade34b757627071fe70de167cc4bbc0?context=explore)

## Problem Details:

Build [9d15839](https://github.com/ckan/ckan-solr/commit/9d158391feb05d425b8d513730c0f03b2c11394d) [v20241212](https://github.com/ckan/ckan-solr/tree/refs/tags/v20241212) [CKAN 2.10 with Solr 9](https://github.com/ckan/ckan-solr/actions/workflows/ckan210-solr9.yml) 
https://github.com/ckan/ckan-solr/actions/runs/12294338995/job/34308921730
```ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.11. Supported versions are [2.8, 2.9, 2.10]```

Yet was still pushed to docker container register.

I don't see workflows for CKAN 2.9 container images but these were also updated in the last 24hours. 

## External build's displaying issue

My build's for ckanext-validation which passed the [day before 2.9 green](https://github.com/ckan/ckanext-validation/actions/runs/12290516472/attempts/1):
Today:
2.10 failure on setup: https://github.com/ckan/ckanext-validation/actions/runs/12290516472/job/34348538444
```ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.11. Supported versions are [2.8, 2.9, 2.10]```
2.9 failure on setup: https://github.com/ckan/ckanext-validation/actions/runs/12290516472/job/34348538721
```ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.11. Supported versions are [2.8, 2.9, 2.10]```

## Related
https://github.com/ckan/ckan-solr/issues/12

**Comment by amercader** [comment]
All images have the relevant schema version for the CKAN version they are targeting. I added another extra check to test this in https://github.com/ckan/ckan-solr/pull/14
